# Generated by Django 6.0.6 on 2026-06-07 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_alter_transaction_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='total_buy_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='total_sell_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
